import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { Sparkles, ArrowLeft, ShieldCheck, AlertTriangle } from 'lucide-react';
import { PageHeader } from '../../components/layout/PageHeader';
import { Card } from '../../components/ui/Card';
import { Badge } from '../../components/ui/Badge';
import { Button } from '../../components/ui/Button';
import { StatusPill } from '../../components/ui/StatusPill';
import { VerificationReport } from '../../components/shared/VerificationReport';
import { formatDate } from '../../lib/formatters';
import { useInsightDetail, useVerificationReport } from '../../hooks/useAnalytics';
import { useJobPoll } from '../../hooks/useJobPoll';
import { api } from '../../api/client';

export const InsightDetailPage: React.FC = () => {
  const { insightId } = useParams<{ insightId: string }>();
  const navigate = useNavigate();

  const [verifyJobId, setVerifyJobId] = useState<string | null>(null);

  const { data: insight, isLoading, isError } = useInsightDetail(insightId);
  const { data: report, refetch: refetchReport } = useVerificationReport(insightId);

  // Poll for verification job completion
  const { data: jobStatus } = useJobPoll(verifyJobId);

  useEffect(() => {
    if (jobStatus?.status === 'completed' || jobStatus?.status === 'error') {
      setVerifyJobId(null);
      refetchReport();
    }
  }, [jobStatus, refetchReport]);

  async function handleVerify() {
    if (!insightId) return;
    try {
      const job = await api.verifyInsight(insightId);
      setVerifyJobId(job.job_id);
    } catch (e: unknown) {
      console.error('Failed to trigger verification:', e);
    }
  }

  if (isLoading) {
    return (
      <div className="p-8 text-center space-y-4 max-w-xl mx-auto">
        <p className="text-sm text-[var(--color-text-subtle)]">Loading insight details…</p>
      </div>
    );
  }

  if (isError || !insight) {
    return (
      <div className="p-8 text-center space-y-4 max-w-xl mx-auto">
        <p className="text-sm text-red-600 font-medium">Failed to load insight details.</p>
        <Button variant="outline" onClick={() => navigate('/ai/insights')}>
          Back to Insights
        </Button>
      </div>
    );
  }

  return (
    <div className="p-4 sm:p-6 space-y-6 max-w-7xl mx-auto">
      <button
        onClick={() => navigate('/ai/insights')}
        className="inline-flex items-center gap-1 text-xs font-semibold text-[var(--color-primary-500)] hover:underline"
      >
        <ArrowLeft size={14} /> Back to Insights List
      </button>

      <PageHeader
        title={insight.summary ? `Insight: ${insight.summary.slice(0, 70)}…` : 'AI Discourse Insight'}
        description={`Generated by ${insight.llm_provider} (${insight.llm_model}) on ${formatDate(insight.generated_at)}`}
        actions={
          <div className="flex items-center gap-2">
            <StatusPill status={insight.generation_status} />
            <Badge variant="outline" size="md">
              {insight.insight_type.replace(/_/g, ' ')}
            </Badge>
          </div>
        }
      />

      {/* Summary Box */}
      <Card className="space-y-3 bg-amber-50/50 border-amber-200">
        <div className="flex items-center gap-2 text-amber-900 font-bold text-sm">
          <Sparkles size={16} className="text-amber-600" />
          <span>Executive Synthesis</span>
        </div>
        <p className="text-sm text-slate-800 leading-relaxed font-medium">
          {insight.summary || 'Summary unavailable.'}
        </p>
      </Card>

      {/* Grounded Findings List */}
      <div className="space-y-4">
        <h3 className="font-heading font-bold text-base text-[var(--color-text-main)]">
          Grounded Findings ({insight.findings?.length || 0})
        </h3>

        <div className="space-y-3">
          {insight.findings?.map((finding, idx) => (
            <Card key={finding.finding_id || idx} className="space-y-2 border-slate-200">
              <div className="flex items-start justify-between gap-3">
                <div className="flex items-start gap-2.5">
                  <span className="w-5 h-5 rounded-full bg-blue-100 text-blue-800 font-bold text-xs flex items-center justify-center shrink-0 mt-0.5 font-mono">
                    {idx + 1}
                  </span>
                  <p className="text-xs sm:text-sm font-medium text-slate-900 leading-relaxed">
                    {finding.text}
                  </p>
                </div>
                <Badge variant="primary" size="sm">
                  Confidence: {finding.confidence}
                </Badge>
              </div>

              {finding.evidence_ids && finding.evidence_ids.length > 0 && (
                <div className="pl-7 flex flex-wrap items-center gap-2 text-xs text-[var(--color-text-subtle)]">
                  <span className="font-medium">Cited Evidence:</span>
                  {finding.evidence_ids.map((evId) => (
                    <span key={evId} className="font-mono bg-slate-100 px-2 py-0.5 rounded text-[11px] text-slate-700">
                      {evId.slice(0, 8)}…
                    </span>
                  ))}
                </div>
              )}
            </Card>
          ))}
        </div>
      </div>

      {/* Discourse Interpretation & Bounded Limitations */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {insight.discourse_interpretation && (
          <Card className="space-y-2">
            <h4 className="font-heading font-bold text-sm text-[var(--color-text-main)]">
              Discourse Interpretation
            </h4>
            <p className="text-xs text-[var(--color-text-muted)] leading-relaxed">
              {insight.discourse_interpretation}
            </p>
          </Card>
        )}

        {insight.limitations && (
          <Card className="space-y-2 bg-slate-50 border-slate-200">
            <div className="flex items-center gap-1.5 text-slate-800 font-bold text-sm">
              <AlertTriangle size={15} className="text-amber-600" />
              <span>Bounded Limitations & Scope</span>
            </div>
            <p className="text-xs text-slate-600 leading-relaxed">
              {insight.limitations}
            </p>
          </Card>
        )}
      </div>

      {/* Verification & Faithfulness Report Panel */}
      <div className="space-y-4 border-t border-slate-200 pt-6">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
          <div className="space-y-0.5">
            <h3 className="font-heading font-bold text-base text-[var(--color-text-main)] flex items-center gap-2">
              <ShieldCheck size={18} className="text-emerald-600" />
              Faithfulness & Verification Report
            </h3>
            <p className="text-xs text-[var(--color-text-subtle)]">
              Atomic claim-by-claim verification evaluating LLM grounding against retrieved comment evidence.
            </p>
          </div>

          <Button
            size="sm"
            variant="outline"
            onClick={handleVerify}
            isLoading={Boolean(verifyJobId)}
          >
            {report ? 'Re-run Verification' : 'Verify Insight Faithfulness'}
          </Button>
        </div>

        {report ? (
          <VerificationReport report={report} />
        ) : (
          <Card className="text-center p-6 text-xs text-[var(--color-text-subtle)] bg-slate-50 border-slate-200">
            Faithfulness report has not been computed yet for this insight. Click <strong>Verify Insight Faithfulness</strong> to run atomic claim verification.
          </Card>
        )}
      </div>
    </div>
  );
};

export default InsightDetailPage;
