import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Sparkles } from 'lucide-react';
import { PageHeader } from '../../components/layout/PageHeader';
import { ScopeIndicator } from '../../components/layout/ScopeIndicator';
import { GlobalFilterBar } from '../../components/filters/GlobalFilterBar';
import { InsightCard } from '../../components/shared/InsightCard';
import { Skeleton } from '../../components/ui/Skeleton';
import { EmptyState } from '../../components/ui/EmptyState';
import { useInsights, usePrograms } from '../../hooks/useAnalytics';

export const InsightsPage: React.FC = () => {
  const navigate = useNavigate();
  const [selectedProg, setSelectedProg] = useState<string | null>(null);

  const { data: insights, isLoading } = useInsights(selectedProg);
  const { data: programs } = usePrograms();

  return (
    <div className="p-4 sm:p-6 space-y-6 max-w-7xl mx-auto">
      <PageHeader
        title="Grounded AI Insights"
        description="Structured discourse summaries and findings generated by LLM and backed by comment evidence."
      />

      <GlobalFilterBar />
      <ScopeIndicator />

      {/* Program Scope Filter bar */}
      <div className="flex items-center justify-between gap-4 bg-white border border-[var(--color-border)] rounded-[var(--radius-card)] p-3 shadow-xs">
        <div className="flex items-center gap-2 text-xs font-semibold text-[var(--color-text-main)]">
          <Sparkles size={15} className="text-amber-500" />
          <span>Filter Insights:</span>
        </div>

        <div className="min-w-[200px] max-w-xs">
          <select
            value={selectedProg || ''}
            onChange={(e) => setSelectedProg(e.target.value || null)}
            className="w-full bg-slate-50 border border-slate-200 rounded-[var(--radius-input)] px-3 py-1.5 text-xs font-medium text-[var(--color-text-main)] focus:bg-white"
          >
            <option value="">All Programs</option>
            {programs?.map((p) => (
              <option key={p.id} value={p.id}>
                {p.name} ({p.channel_name})
              </option>
            ))}
          </select>
        </div>
      </div>

      {/* Insights Grid */}
      {isLoading ? (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {[1, 2, 3].map((i) => (
            <div key={i} className="p-5 bg-white border border-slate-200 rounded-lg space-y-3">
              <Skeleton height={20} width="60%" />
              <Skeleton height={14} width="90%" />
              <Skeleton height={40} width="100%" />
            </div>
          ))}
        </div>
      ) : insights && insights.length > 0 ? (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {insights.map((ins) => (
            <InsightCard
              key={ins.insight_id}
              insight={ins}
              onSelect={(id) => navigate(`/ai/insights/${id}`)}
            />
          ))}
        </div>
      ) : (
        <EmptyState
          icon={Sparkles}
          title="No AI Insights Generated Yet"
          description="Grounded AI insights synthesize comment evidence into structured findings. Use Evidence Explorer to retrieve evidence and generate new insights."
          actionLabel="Go to Evidence Explorer"
          onAction={() => navigate('/ai/evidence')}
        />
      )}
    </div>
  );
};

export default InsightsPage;
