import React from 'react';
import { PageHeader } from '../../components/layout/PageHeader';
import { Card } from '../../components/ui/Card';
import { Badge } from '../../components/ui/Badge';
import { BookOpen, Shield, Brain, Database, GitBranch } from 'lucide-react';

function Section({ icon, title, children }: { icon: React.ReactNode; title: string; children: React.ReactNode }) {
  return (
    <Card className="space-y-3 border-slate-200">
      <div className="flex items-center gap-2.5 border-b border-slate-100 pb-2">
        <div className="text-[var(--color-primary-500)]">{icon}</div>
        <h2 className="text-sm font-semibold text-[var(--color-text-main)]">{title}</h2>
      </div>
      <div className="space-y-2 text-xs text-[var(--color-text-muted)] leading-relaxed">
        {children}
      </div>
    </Card>
  );
}

export const MethodologyPage: React.FC = () => {
  return (
    <div className="p-4 sm:p-6 space-y-6 max-w-4xl mx-auto">
      <PageHeader
        title="Methodology & Governance"
        description="How Public Pulse collects, classifies, and analyses Sri Lankan public discourse from YouTube comments."
      />

      {/* System overview */}
      <Section icon={<Brain size={18} />} title="System Overview">
        <p>
          Public Pulse is a grounded LLM research system tracking public discourse from Sri Lankan TV news
          YouTube channels. It ingests public comments, applies multilingual NLP classification,
          and surfaces structured analytical insights grounded in comment evidence.
        </p>
        <p>
          The system is designed as a <strong>civic-intelligence analytics platform</strong>, not a
          sentiment aggregator. All stance classification is orientation-based (stance toward subject matter),
          not valence-based (positive/negative emotion).
        </p>
      </Section>

      {/* Data collection */}
      <Section icon={<Database size={18} />} title="Data Collection & Pre-processing">
        <p>
          Public comments are collected from YouTube via YouTube Data API v3. Only public comments
          from selected Sri Lankan TV news programme channels are included.
        </p>
        <p>
          Comments undergo validation: deduplication by comment ID, language detection,
          minimum length thresholds, and spam heuristics. Only comments passing all validation
          gates are included in analytics (`valid=true`).
        </p>
      </Section>

      {/* Topic classification */}
      <Section icon={<GitBranch size={18} />} title="Topic Classification (Layer 1)">
        <p>
          Topic classification assigns each comment to one of the 5 macro-topic taxonomy categories.
          Categories cover major Sri Lankan public discourse themes including economic governance,
          foreign affairs, governance & political accountability, law & justice, and media credibility.
        </p>
        <p>
          Classification uses a fine-tuned <strong>XLM-RoBERTa</strong> model capable of processing
          Sinhala, Tamil, and English comments without translation.
        </p>
        <div className="flex flex-wrap gap-2 pt-1">
          <Badge variant="primary">XLM-RoBERTa</Badge>
          <Badge variant="outline">Multilingual</Badge>
          <Badge variant="outline">Unicode NFC</Badge>
        </div>
      </Section>

      {/* Stance classification */}
      <Section icon={<GitBranch size={18} />} title="Stance Classification (Layer 2)">
        <p>
          Stance classification assigns each topic-classified comment one of three orientations:
        </p>
        <ul className="list-none space-y-1 pl-2 font-medium">
          <li className="text-[var(--color-crit)]">
            • <strong>CRITICAL</strong> — commenter expresses concern, dissatisfaction, or opposition.
          </li>
          <li className="text-[var(--color-neut)]">
            • <strong>NEUTRAL</strong> — commenter presents information, questions, or observations.
          </li>
          <li className="text-[var(--color-supp)]">
            • <strong>SUPPORTIVE</strong> — commenter expresses agreement, approval, or endorsement.
          </li>
        </ul>
        <p className="pt-1">
          <strong>Stance is not sentiment.</strong> Sarcasm is merged into CRITICAL orientation and is not presented as an independent dimension. Layer 3 sub-issue classification was permanently removed.
        </p>
      </Section>

      {/* Evidence & LLM */}
      <Section icon={<Brain size={18} />} title="Grounded LLM Insight Generation">
        <p>
          Insights are generated by a retrieval-augmented LLM pipeline:
        </p>
        <ol className="list-decimal list-inside space-y-1">
          <li>A natural-language query is embedded using a sentence transformer.</li>
          <li>The top-k most semantically similar comments are retrieved from vector index.</li>
          <li>Retrieved evidence (`text_clean`) is provided to the LLM.</li>
          <li>The LLM generates structured insights: summary, findings, discourse interpretation, limitations.</li>
        </ol>
        <p className="pt-1">
          Insights are grounded — every claim cites specific evidence IDs. Comment text displayed
          in evidence panels is always <strong>text_clean</strong> (sanitised), never raw text.
        </p>
      </Section>

      {/* Faithfulness verification */}
      <Section icon={<Shield size={18} />} title="Faithfulness Verification">
        <p>
          Generated insights undergo atomic claim verification checking each claim against the retrieved evidence corpus to assign verdicts (SUPPORTED, PARTIALLY_SUPPORTED, UNSUPPORTED, CONTRADICTED).
        </p>
      </Section>

      {/* Privacy */}
      <Section icon={<Shield size={18} />} title="Privacy & Data Protection">
        <p>
          Public Pulse is designed with privacy by default:
        </p>
        <ul className="list-disc list-inside space-y-1">
          <li>No usernames, author hashes, or PII are exposed in any dashboard view or stored in frontend state.</li>
          <li>Comment text is displayed only in Evidence panels (`text_clean`), never raw text (`text_raw`).</li>
          <li>All analytics are aggregate server-side aggregations.</li>
        </ul>
      </Section>

      {/* Footer info */}
      <div className="flex items-center gap-2 pt-2 border-t border-slate-200 text-[11px] text-[var(--color-text-subtle)] font-mono">
        <BookOpen size={13} className="text-slate-400" />
        <span>Public Pulse Platform — Phase 12C Redesign • Methodology v1.0</span>
      </div>
    </div>
  );
};

export default MethodologyPage;
